### ISSUE TITLE
Inquiry about Availability of presto-maven-plugin-0.5 in Maven Central Repository

### ISSUE THREAD

**Issue by lutongzero** [prestodb/presto-maven-plugin#17]
I noticed that the current tag branch has presto-maven-plugin-0.5, but it doesn't seem to exist in the Maven Central Repository. Could you please provide guidance on its availability or any plans for its release to Maven Central? Thank you!

**Comment by tdcmeehan** [comment]
We're working on publishing this artifact, sorting through some issues with Maven central. CC: @wanglinsong

**Comment by wanglinsong** [comment]
Yes. I am looking into the issue.

**Comment by wanglinsong** [comment]
https://ci.ahana.dev/blue/organizations/jenkins/oss-presto-release%2Fpresto-maven-plugin/detail/master/4/pipeline/30/

**Comment by wanglinsong** [comment]
https://github.com/prestodb/presto-maven-plugin/pull/18
